/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.ArduinoSerial;

/**
 *
 * @author sepho
 */
public class ViewAlvo extends javax.swing.JFrame {

    ArduinoSerial arduino = new ArduinoSerial("COM4");

    /**
     * Creates new form ViewAlvo
     */
    public ViewAlvo() {
        initComponents();
        arduino.initialize();
   // setExtendedState(java.awt.Frame.NORMAL);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn135 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn180 = new javax.swing.JButton();
        btn90 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle do Alvo - Extensão UEMG 2022");
        setMaximumSize(new java.awt.Dimension(640, 420));
        setMinimumSize(new java.awt.Dimension(640, 420));
        setPreferredSize(new java.awt.Dimension(640, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        btn135.setBackground(new java.awt.Color(255, 51, 0));
        btn135.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn135.setForeground(new java.awt.Color(255, 255, 255));
        btn135.setText("135º");
        btn135.setPreferredSize(new java.awt.Dimension(130, 70));
        btn135.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn135ActionPerformed(evt);
            }
        });
        getContentPane().add(btn135);
        btn135.setBounds(160, 300, 130, 70);

        btn45.setBackground(new java.awt.Color(255, 51, 0));
        btn45.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn45.setForeground(new java.awt.Color(255, 255, 255));
        btn45.setText("45º");
        btn45.setMaximumSize(new java.awt.Dimension(48, 48));
        btn45.setMinimumSize(new java.awt.Dimension(48, 48));
        btn45.setPreferredSize(new java.awt.Dimension(130, 70));
        btn45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn45ActionPerformed(evt);
            }
        });
        getContentPane().add(btn45);
        btn45.setBounds(160, 200, 130, 70);

        btn0.setBackground(new java.awt.Color(255, 51, 0));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0º");
        btn0.setMaximumSize(new java.awt.Dimension(48, 48));
        btn0.setMinimumSize(new java.awt.Dimension(48, 48));
        btn0.setPreferredSize(new java.awt.Dimension(130, 70));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0);
        btn0.setBounds(240, 110, 130, 70);

        btn180.setBackground(new java.awt.Color(255, 51, 0));
        btn180.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn180.setForeground(new java.awt.Color(255, 255, 255));
        btn180.setText("180º");
        btn180.setPreferredSize(new java.awt.Dimension(130, 70));
        btn180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn180ActionPerformed(evt);
            }
        });
        getContentPane().add(btn180);
        btn180.setBounds(330, 300, 130, 70);

        btn90.setBackground(new java.awt.Color(255, 51, 0));
        btn90.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn90.setForeground(new java.awt.Color(255, 255, 255));
        btn90.setText("90º");
        btn90.setPreferredSize(new java.awt.Dimension(130, 70));
        btn90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn90ActionPerformed(evt);
            }
        });
        getContentPane().add(btn90);
        btn90.setBounds(330, 200, 130, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROLE DO ALVO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 30, 270, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background-2426328_640.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 670, 400);

        getAccessibleContext().setAccessibleDescription("Tela para controle da posição do alvo. Projeto de extensão - Sistemas de Automação - Engenharia da Computação - UEMG - 2022");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn45ActionPerformed
        arduino.send("1");
    }//GEN-LAST:event_btn45ActionPerformed

    private void btn90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn90ActionPerformed
        arduino.send("2");

    }//GEN-LAST:event_btn90ActionPerformed

    private void btn135ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn135ActionPerformed
        arduino.send("3");
    }//GEN-LAST:event_btn135ActionPerformed

    private void btn180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn180ActionPerformed
        arduino.send("4");
    }//GEN-LAST:event_btn180ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        arduino.send("0");
    }//GEN-LAST:event_btn0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAlvo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn135;
    private javax.swing.JButton btn180;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn90;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
